
const Map<String, Map<String, String>> languages = {
  "tr" : tr
};

const Map<String, String> tr = {
  "email" : "Email",
  "phone" : "Telefon",
  "password" : "Şifre",
  "password_again" : "Şifre Tekrar",
  "forgot_password" : "Şifremi Unuttum",
  "login" : "Giriş Yap",
  "or" : "ya da",
  "user_agreement" : " Kullanıcı Sözleşmesi",
  "by_continuing" : "Devam ederek",
  "accepted_user_agreement" : "'ni kabul etmiş olacaksınız.",
  "sign_up" : "Kayıt Ol",
  "already_have_account" : "Zaten hesabım var",
  "no_account" : "Hesabım yok",
  "add_photo" : "Fotoğraf ekle",
  "name" : "İsim",
  "surname" : "Soyisim",
  "continue" : "Devam Et",
  "pick_role" : "Bir Rol Seçiniz",
  "carrier" : "Taşıyıcı",
  "shipper" : "Yük Sahibi",
  "license_front" : "Ehliyet Ön Yüz",
  "license_back" : "Ehliyet Arka Yüz",
  "id_front" : "Kimlik Ön Yüz",
  "id_back" : "Kimlik Arka Yüz",
  "src" : "SRC belgenizi yükleyiniz",
  "psiko" : "Psikoteknik belgenizi yükleyiniz",
  "confirm" : "Onayla",
  "input_email" : "Email adresinizi giriniz.",
  "input_password" : "Şifrenizi giriniz.",
  "input_password_again" : "Şifrenizi tekrar giriniz.",
  "input_phone" : "Telefon numaranızı giriniz.",
  "input_name" : "İsminizi giriniz.",
  "input_surname" : "Soyisminizi giriniz.",
  "upload_necessary_files" : "Gerekli Dosyaları Yükleyiniz",
  "fill_out" : "Bilgilerinizi Giriniz",
  "search" : "Arama Yap",
  "discover" : "Keşfet",
  "find_load" : "Yük Bul",
  "find_loads" : "Yükleri Bul",
  "rest" : "Dinlen",
  "fuel" : "Yakıt Bul",
  "my_vehicles" : "Araçlarım",
  "new_vehicle" : "Yeni Araç Ekle",
  "new_post_with_vehicle" : "Araç için yeni ilan ekle",
  "add_new_truck" : "Yeni Araç Ekle",
  "save" : "Kaydet",
  "length" : "Uzunluk",
  "weight" : "Ağırlık",
  "price" : "Fiyat",
  "equipment_limits" : "Yük Sınırı",
  "full" : "Tam",
  "partial" : "Kısmi",
  "truck_name" : "Araç İsmi",
  "enter_truck_name" : "Araç ismi giriniz.",
  "enter_description" : "Bir açıklama yazınız",
  "description" : "Açıklama",
  "enter_truck_description" : "Araç için bir açıklama yazınız.",
  "truck_details" : "Araç Detayları",
  "origin" : "Başlangıç",
  "target" : "Hedef",
  "vehicle_type" : "Araç Türü",
  "start_date" : "Başlangıç Tarihi",
  "end_date" : "Bitiş Tarihi",
  "pick_a_date" : "Bir tarih seçiniz",
  "max_age" : "Max. Yayın Tarihi",
  "published_date" : "Yayın Tarihi",
  "pick_a_type" : "Araç Türü Seçiniz",
  "pick_an_age" : "Maksimum bir yayın tarihi seçiniz",
  "cancel" : "İptal",
  "result" : "Sonuç",
  "edit_search" : "Aramayı Düzenle",
  "request_sent" : "İstek Gönderildi",
  "est" : "Ort.",
  "load_details" : "Yük Detayları",
  "take_the_job" : "İşi Al",
  "call" : "Ara",
  "total" : "Toplam",
  "distance" : "Mesafe",
  "vehicle_details" : "Araç Detayları",
  "shipping_details" : "Nakliye Detayları",
  "rate_details" : "Fiyatlandırma Detayları",
  "company_details" : "Şirket Detayları",
  "full_partial" : "Tam/Kısmi",
  "shipping_type" : "Yük Türü",
  "pick_up_date" : "Teslim Alma",
  "dock_date" : "Teslim Etme",
  "reference" : "Referans Kodu",
  "per_km" : "KM Başına",
  "company_name" : "Şirket İsmi",
  "location" : "Konum",
  "rating" : "Değerlendirme",
  "registration" : "Ruhsat belgenizi yükleyiniz",
  "i_am_a_broker" : "Nakliye komisyoncusuyum.\nYük sahibi değilim.",
  "my_loads" : "Yüklerim",
  "new_post" : "Yeni Yük Oluştur",
  "start_time" : "Alma Saati",
  "end_time" : "Teslim Saati",
  "pick_a_time" : "Bir saat seçiniz",
  "contact_phone" : "İletişim Numarası",
  "enter_contact_phone" : "Bir iletişim numarası giriniz",
  "enter_price" : "Bir fiyat giriniz",
  "post_your_car" : "Aracı Yayınla",
  "registered_city" : "Kayıtlı Olduğu Şehir",
  "enter_registered_city" : "Aracıın kayıtlı olduğu şehri seçiniz",
  "bulk_or_palletized" : "Yük Dökmeli mi Paletli mi?",
  "bulk" : "Dökmeli",
  "palletized" : "Paletli",
  "load_type" : "Yük Tipi",
  "post_new_load" : "Yeni Yük Oluştur",
  "load_volume" : "Yük Hacmi",
  "problem_signing_up" : "Kayıt sırasında bir hata oluştu!",
  "problem_creating_new_load" : "Yeni yük oluştururken bir hata oluştu!",
  "new_load_created" : "Yeni yük başarıyla listelendi.",
  "enter_weight" : "Ağırlık giriniz.",
  "enter_length" : "Uzunluk giriniz.",
  "enter_volume" : "Hacim giriniz.",
  "volume" : "Hacim",
  "end_date_must_be_after_than_first_date" : "Bitiş tarihi başlangıç tarihi ile aynı gün veya sonrasında olmalıdır.",
  "bus" : "Otobüs",
  "truck" : "Kamyon",
  "car" : "Araba",
  "pick_a_phone_number" : "Bir iletişim numarası seçiniz",
  "add_new_phone_number" : "Yeni numara ekle",
  "available" : "Aktif",
  "no_loads_found" : "Henüz bir yük eklemediniz. Yeni bir yük oluşturabilirsiniz.",
};