// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0ZSyv2zd-S6cPbLw4GombGk_tBQurg0k',
    appId: '1:317562345526:web:1c40be37c0d4abad3d6097',
    messagingSenderId: '317562345526',
    projectId: 'yukbultr',
    authDomain: 'yukbultr.firebaseapp.com',
    storageBucket: 'yukbultr.appspot.com',
    measurementId: 'G-VKHGZGR9ZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5NDyppKB3hCi9RlyIWrQDO1lhl2kgFG0',
    appId: '1:317562345526:android:0048e0fdc74a45693d6097',
    messagingSenderId: '317562345526',
    projectId: 'yukbultr',
    storageBucket: 'yukbultr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZg_ZZdVGiLpdwBs3pbnP6sl4JaEquLY8',
    appId: '1:317562345526:ios:114a5f1a9fba96ff3d6097',
    messagingSenderId: '317562345526',
    projectId: 'yukbultr',
    storageBucket: 'yukbultr.appspot.com',
    iosBundleId: 'com.kamyon.kamyon',
  );
}
